#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/business_db?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: xxxx

# dubbo配置,当应用时job应用时,关闭dubbo 提供者
dubbo:
  enable: false
# consistent-invoker主要配置
consistent-invoker:
  enable: true
  # 是否启动xxl job,为true时将初始化XXlJob实现类到spring 容器中
  enableJob: true
  # 是否注册重试服务提供者到dubbo中，为true时需配置dubbo、注册中心等配置,默认是true,当时job应用时，设置为false
  enableRetryProvider: false
  # 使用业务数据库，即spring的默认数据源
  use-default-datasource: false

  # 选配，当use-default-datasource=false时必须配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consistent_call_db?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: xxxx

xxl:
  job:
    executor:
      #执行器app的名称，和控制台保持一致
      appname: xxl-job-executor-sample
      #有效使用该地址作为注册地址 为空使用内嵌服务地址
      address:
      #执行器IP 默认自动获取
      ip: localhost
      #执行器端口 小于等于0 自动获取 ，默认 9999 ，配置多个执行器时，需要配置不同的执行器端口
      port: 9999
      #执行器日志保持天数 -1永久生效
      logretentiondays: 30
      #执行器日志文件保持地址 ，为空使用默认保存地址
      logpath: /data/logs/xxl-job-log/executor
    admin:
      #调度中心部署地址，多个配置 ，分割
      addresses: http://127.0.0.1:8080/xxl-job-admin

